package realizeapp

import (
	"context"
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/jbaruch/agentic-context-registry/internal/adapter"
	"github.com/jbaruch/agentic-context-registry/internal/adapter/claudecode"
	"github.com/jbaruch/agentic-context-registry/internal/adapter/codex"
	"github.com/jbaruch/agentic-context-registry/internal/adapter/cursor"
	"github.com/jbaruch/agentic-context-registry/internal/cli"
	"github.com/jbaruch/agentic-context-registry/internal/dependency"
	"github.com/jbaruch/agentic-context-registry/internal/manifest"
	"github.com/jbaruch/agentic-context-registry/internal/preserve"
	"github.com/jbaruch/agentic-context-registry/internal/realize"
)

// Expected bytes are authored independently of the scanner, including the
// published paragraph and the lookalikes that must survive.
func emphasisToneGuide(root, legacy string) string {
	return "## Anti-Patterns: What to Never Do\n\n" +
		"**`" + root + "/references/ai-anti-patterns.md` is the list.** It names every pattern, with symptoms,\n" +
		"examples, structural variants, and alternatives. Read it there — this file carries no\n" +
		"copy of it. Scan the draft against every pattern during Phase 3 and Phase 4. Zero\ntolerance.\n\n" +
		"Read __`" + legacy + "/references/ai-anti-patterns.md`__.\n\n" +
		"Keep archive**`skills/blog-writer/references/ai-anti-patterns.md`**,\n" +
		"https://example.test/__`skills/blog-writer/references/ai-anti-patterns.md`__,\n" +
		"\"archive **`skills/blog-writer/references/ai-anti-patterns.md`**\", and\n" +
		"**`.tessl/plugins/other/blog-writer/skills/blog-writer/references/ai-anti-patterns.md`**.\n"
}

// Seed observed 0.1.4 generated bytes through the production engine, which
// records their ownership, then upgrade through CLI check/dry-run/realize.
// Real published-package and native-client acceptance remains a separate gate.
func TestCLIUpgradesEmphasizedReferences(t *testing.T) {
	t.Parallel()
	base, packageRoot, state, _ := realizationFixture(t)
	project := filepath.Join(base, "consumer with spaces")
	const source = "github:jbaruch/blog-writer"
	state.Project.Dependencies[0].Source = source
	state.Lock.Dependencies[0].Source = source
	state.Project.Agents = []string{"claude-code", "codex", "cursor"}
	state.Project.SharedSkills = true
	state.Project.Freshness = "none"
	value := manifest.Manifest{
		Name: "jbaruch/blog-writer", Source: manifest.Source{TesslIdentity: "jbaruch/blog-writer"},
		Artifacts: manifest.Artifacts{Skills: []manifest.SkillArtifact{{ID: "blog-writer", Path: "skills/blog-writer"}}},
	}
	original := emphasisToneGuide("skills/blog-writer", ".tessl/plugins/jbaruch/blog-writer/skills/blog-writer")
	const destination = "# Anti-patterns\n\nRead the complete list here.\n"
	for relative, content := range map[string]string{
		"SKILL.md":                       "---\nname: blog-writer\ndescription: Write a blog post.\n---\n\n# Blog writer\n",
		"references/tone-guide.md":       original,
		"references/ai-anti-patterns.md": destination,
		"scripts/check.sh":               "#!/bin/sh\nset -eu\nprintf 'helper preserved\\n'\n",
	} {
		mode := os.FileMode(0o644)
		if relative == "scripts/check.sh" {
			mode = 0o755
		}
		writeFixture(t, filepath.Join(packageRoot, "skills/blog-writer", relative), []byte(content), mode)
	}
	for relative, content := range map[string]string{
		"CLAUDE.md": "User Claude guidance\n", "AGENTS.md": "User agent guidance\n",
		".claude/settings.json": "{\"permissions\":{\"allow\":[\"Read\"]}}\n",
		".codex/config.toml":    "model = \"user-choice\"\n",
		".cursor/hooks.json":    "{\"version\":1,\"hooks\":{}}\n",
	} {
		writeFixture(t, filepath.Join(project, relative), []byte(content), 0o644)
	}
	initRepository(t, project)
	if err := dependency.WriteState(project, state); err != nil {
		t.Fatal(err)
	}
	packages := []adapter.Package{{Source: source, Root: os.DirFS(packageRoot), Manifest: value}}
	coordinator, err := adapter.NewCoordinator(preserve.NewCompiler(), claudecode.New(), codex.New(), cursor.New())
	if err != nil {
		t.Fatal(err)
	}
	previous := realize.Ledger{SchemaVersion: realize.CurrentLedgerSchemaVersion}
	intents, err := coordinator.Realize(context.Background(), adapter.NewFSSnapshot(os.DirFS(project)), packages, previous)
	if err != nil {
		t.Fatal(err)
	}
	shared, err := adapter.SharedSkillIntents(packages)
	if err != nil {
		t.Fatal(err)
	}
	intents = append(intents, shared...)
	oldVersions := map[string]string{"claude-code": "1.0.2", "codex": "1.0.1", "cursor": "1.0.1", "coordinator": "2"}
	for index := range intents {
		intent := &intents[index]
		if strings.HasSuffix(intent.Path, "/references/tone-guide.md") {
			intent.Content = []byte(original)
		}
		for entry := range intent.Entries {
			intent.Entries[entry].AdapterVersion = oldVersions[intent.Entries[entry].Adapter]
			intent.Entries[entry].ManagedHash = fmt.Sprintf("sha256:%x", sha256.Sum256(intent.Content))
		}
	}
	if _, err := realize.NewEngine().Run(project, previous, intents, realize.ModeApply, func(next realize.Ledger) error {
		encoded, err := realize.EncodeLedger(next)
		if err != nil {
			return err
		}
		state.Lock.Realization = encoded
		return dependency.WriteState(project, state)
	}); err != nil {
		t.Fatal(err)
	}
	for _, surface := range []string{".agents", ".claude", ".codex", ".cursor"} {
		filename := surface + "/skills/acr__jbaruch__blog-writer__blog-writer/references/tone-guide.md"
		if got := string(readProjectFile(t, project, filename)); got != original {
			t.Fatalf("historical %s = %q, want observed 0.1.4 content %q", filename, got, original)
		}
	}
	before := snapshotClaudeUpgrade(t, project)
	packageBefore := snapshotClaudeUpgrade(t, packageRoot)
	application := &Application{service: NewService(fixtureLoader{root: packageRoot, manifest: value}), fallback: cli.UnavailableApplication{}}
	for _, args := range [][]string{{"check"}, {"realize", "--dry-run"}} {
		stdout, stderr, code := runCLI(t, application, append(args, "--project", project, "--json")...)
		if args[0] == "check" {
			if code != cli.ExitChanges || !strings.Contains(stderr, `"code":"realization_changes"`) {
				t.Fatalf("old check: exit %d, stdout %s, stderr %s", code, stdout, stderr)
			}
		} else if code != cli.ExitSuccess || stderr != "" || !strings.Contains(stdout, `"ledgerChanged":true`) {
			t.Fatalf("upgrade dry-run: exit %d, stdout %s, stderr %s", code, stdout, stderr)
		}
		if !reflect.DeepEqual(snapshotClaudeUpgrade(t, project), before) {
			t.Fatalf("%v wrote project files", args)
		}
	}
	stdout, stderr, code := runCLI(t, application, "realize", "--project", project, "--json")
	if code != cli.ExitSuccess || stderr != "" {
		t.Fatalf("upgrade: exit %d, stdout %s, stderr %s", code, stdout, stderr)
	}
	after := snapshotClaudeUpgrade(t, project)
	for _, surface := range []string{".agents", ".claude", ".codex", ".cursor"} {
		root := surface + "/skills/acr__jbaruch__blog-writer__blog-writer"
		tone := root + "/references/tone-guide.md"
		if got, want := string(readProjectFile(t, project, tone)), emphasisToneGuide(root, root); got != want {
			t.Fatalf("%s complete content = %q, want %q", tone, got, want)
		}
		// Open the destinations actually named by both rebased code spans.
		for _, line := range strings.Split(string(readProjectFile(t, project, tone)), "\n") {
			if strings.Contains(line, "` is the list.**") || strings.HasPrefix(line, "Read __`") {
				_, rest, _ := strings.Cut(line, "`")
				reference, _, _ := strings.Cut(rest, "`")
				if got := string(readProjectFile(t, project, reference)); got != destination {
					t.Fatalf("%s points to wrong content: %q", tone, got)
				}
			}
		}
		delete(before, filepath.FromSlash(tone))
		delete(after, filepath.FromSlash(tone))
	}
	delete(before, dependency.LockFilename)
	delete(after, dependency.LockFilename)
	if !reflect.DeepEqual(before, after) || !reflect.DeepEqual(packageBefore, snapshotClaudeUpgrade(t, packageRoot)) {
		t.Fatal("upgrade changed user settings, prompts, companions, modes or package sources")
	}
	current := snapshotClaudeUpgrade(t, project)
	for _, command := range []string{"check", "realize"} {
		stdout, stderr, code := runCLI(t, application, command, "--project", project, "--json")
		if code != cli.ExitSuccess || stderr != "" || !reflect.DeepEqual(current, snapshotClaudeUpgrade(t, project)) {
			t.Fatalf("%s after upgrade: exit %d, stdout %s, stderr %s; must stay current and idempotent", command, code, stdout, stderr)
		}
	}
	loaded, err := dependency.LoadState(project)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(loaded.Lock.Dependencies, state.Lock.Dependencies) {
		t.Fatal("upgrade changed locked dependencies")
	}
	versions := map[string]string{"claude-code": "1.0.3", "codex": "1.0.3", "cursor": "1.0.2", "coordinator": "3"}
	for _, target := range loadLedger(t, project).Targets {
		for _, entry := range target.Entries {
			if entry.AdapterVersion != versions[entry.Adapter] {
				t.Fatalf("stale version in ledger: %#v", entry)
			}
		}
	}
}
