package producerconvert

import (
	"context"
	"io/fs"
	"os/exec"
	"reflect"
	"strings"
	"testing"
)

func TestNestedOriginalTestsReceivePreservationFilters(t *testing.T) {
	for _, parent := range []string{"tests", "skills/example/tests"} {
		for _, language := range []string{"python-registration", "python-collector", "python-assertion", "python-bypass", "shell", "go"} {
			t.Run(parent+"/"+language, func(t *testing.T) {
				root, opts := fleetFixture(t, fleetCaller)
				opts.Agent = "codex"
				name := parent + "/test_example.py"
				before := "# tessl install other/producer\ndef fail(failures, message):\n    failures.append(message)\ndef test_keep():\n    assert True\nTESTS = [test_keep]\n"
				after := strings.Replace(before, "# tessl install other/producer\n", "", 1)
				switch language {
				case "python-registration":
					after = strings.Replace(after, "TESTS = [test_keep]", "TESTS = []", 1)
				case "python-collector":
					after = strings.Replace(after, "failures.append(message)", "pass", 1)
				case "python-assertion":
					after = strings.Replace(after, "assert True", "pass", 1)
				case "python-bypass":
					after = strings.Replace(after, "def test_keep():", "@unittest.skip(\"weakened\")\ndef test_keep():", 1)
				case "shell":
					name = parent + "/test_example.sh"
					before = "#!/bin/sh\n# tessl install other/producer\nprintf original\n"
					after = "#!/bin/sh\nprintf weakened\n"
				case "go":
					name = parent + "/test_example.go"
					before = "// tessl install other/producer\npackage sample\nfunc testKeep() bool { return false }\n"
					after = "package sample\nfunc testKeep() bool { return true }\n"
				}
				put(t, root, name, before, 0644)
				original := treeAt(t, root)
				proposed := proposal{Edits: []proposedEdit{{Path: name, BeforeDigest: digest([]byte(before)), Action: "replace", Content: after}}}
				_, err := prepareWithProvider(context.Background(), opts, func(context.Context, string, string) (proposal, AgentRun, error) { return proposed, AgentRun{}, nil })
				if err == nil {
					t.Fatal("test weakening accepted")
				}
				if !matches(original, treeAt(t, root)) {
					t.Fatal("refusal changed source")
				}
			})
		}
	}
}

func TestRepositoryFormatsKeepOriginalBytesAndScope(t *testing.T) {
	for _, format := range []string{"ignore", "pyright", "rule"} {
		t.Run(format, func(t *testing.T) {
			root, opts := fleetFixture(t, fleetCaller)
			name, body := ".gitignore", "# Generated by tessl install; tessl.json remains foreign\n.tessl/\n.agents/\n!keep/.tessl/\n"
			switch format {
			case "pyright":
				name = "pyrightconfig.json"
				body = `{"include":[".github/scripts","skills/example/scripts","skills/example/tests"],"pythonVersion":"3.12","typeCheckingMode":"standard","reportMissingImports":"error"}`
				put(t, root, "skills/example/scripts/helper.py", "print('kept')\n", 0644)
				put(t, root, "skills/example/tests/test_keep.py", "assert True\n", 0644)
			case "rule":
				name = "rules/policy.md"
				body = "---\nalwaysApply: false\napplyTo: \"skills/example/** — when checking examples\"\ndescription: Example checks\n---\n# Policy\nKeep every independent check.\n"
				put(t, root, ".tessl-plugin/plugin.json", `{"name":"other/producer","version":"1.2.3","skills":["skills/example"],"rules":["rules/policy.md"]}`, 0644)
			}
			put(t, root, name, body, 0644)
			plan, err := Prepare(opts)
			if err != nil {
				t.Fatal(err)
			}
			if _, err = plan.Apply(); err != nil {
				t.Fatal(err)
			}
			got := treeAt(t, root)[name]
			if string(got.Content) != body || got.Mode != 0644 {
				t.Fatal("configuration bytes/mode changed")
			}
			if format == "rule" {
				// The existing manifest activation parser remains authoritative.
				if len(plan.Report.Artifacts) == 0 || !strings.Contains(read(t, root, "agent-plugin.yaml"), "skills/example/**") {
					t.Fatal("activation scope lost")
				}
			}
		})
	}
}

func TestOwnedReferenceOnlyContentCanBeProposed(t *testing.T) {
	root, opts := fleetFixture(t, fleetCaller)
	opts.Agent = "codex"
	put(t, root, "skills/example/state-schema.md", "# State ownership\nThis skill owns the store schema.\n", 0644)
	name := "skills/example/helper.sh"
	before := "#!/bin/sh\n# Owner: skills/example\nprintf 'same-behavior\\n'\n"
	after := "#!/bin/sh\n# Owner schema: skills/example/state-schema.md\nprintf 'same-behavior\\n'\n"
	put(t, root, name, before, 0755)
	proposed := proposal{Edits: []proposedEdit{{Path: name, BeforeDigest: digest([]byte(before)), Action: "replace", Content: after}}}
	plan, err := prepareWithProvider(context.Background(), opts, func(_ context.Context, _ string, request string) (proposal, AgentRun, error) {
		return proposed, AgentRun{}, nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, err = plan.Apply(); err != nil {
		t.Fatal(err)
	}
	output, err := exec.Command(root + "/" + name).CombinedOutput()
	if err != nil || string(output) != "same-behavior\n" {
		t.Fatalf("helper behavior: %s %v", output, err)
	}
	if !reflect.DeepEqual(treeAt(t, root)[name].Content, []byte(after)) {
		t.Fatal("content adaptation differs")
	}
}

func TestRootAndNestedAdaptationsRetainForeignStateChecks(t *testing.T) {
	for _, parent := range []string{"tests", "skills/example/tests"} {
		t.Run(parent, func(t *testing.T) {
			root, opts := fleetFixture(t, fleetCaller)
			opts.Agent = "codex"
			name := parent + "/test_keep.py"
			before := "# tessl install other/producer\nforeign = 'tessl.json'\ndef test_keep():\n    assert foreign == 'tessl.json'\ntest_keep()\n"
			after := strings.TrimPrefix(before, "# tessl install other/producer\n")
			put(t, root, name, before, 0644)
			plan, err := prepareWithProvider(context.Background(), opts, func(context.Context, string, string) (proposal, AgentRun, error) {
				return proposal{Edits: []proposedEdit{{Path: name, Action: "replace", BeforeDigest: digest([]byte(before)), Content: after}}}, AgentRun{}, nil
			})
			if err != nil {
				t.Fatal(err)
			}
			if _, err = plan.Apply(); err != nil {
				t.Fatal(err)
			}
			if output, err := exec.Command("python3", "-I", "-S", root+"/"+name).CombinedOutput(); err != nil {
				t.Fatalf("retained check: %v %s", err, output)
			}
			if read(t, root, name) != after {
				t.Fatal("foreign-state checks altered")
			}
		})
	}
}

func TestConfigurationClassificationDoesNotHideRuntimeOrMetadata(t *testing.T) {
	for _, scenario := range []string{"executable-ignore", "shell", "markdown-code", "pyright-unknown", "pyright-invalid", "rule-body", "rule-metadata", "rule-activation-invalid", "rule-activation-missing-dash"} {
		t.Run(scenario, func(t *testing.T) {
			root, opts := fleetFixture(t, fleetCaller)
			name, body, mode := ".gitignore", "# tessl install other/producer\n.tessl/\n", 0755
			switch scenario {
			case "shell":
				name = "skills/example/helper.sh"
				body = "#!/bin/sh\ncat .tessl-plugin/plugin.json\n"
			case "markdown-code":
				name = "skills/example/instructions.md"
				mode = 0644
				body = "# Instructions\nRun `cat .tessl-plugin/plugin.json`.\n"
			case "pyright-unknown":
				name = "pyrightconfig.json"
				mode = 0644
				body = `{"include":["skills/example"],"pythonVersion":"3.12","typeCheckingMode":"standard","reportMissingImports":"error","extra":".tessl-plugin/plugin.json"}`
			case "pyright-invalid":
				name = "pyrightconfig.json"
				mode = 0644
				body = `{"include":["skills/example"],"pythonVersion":"tessl install bad","typeCheckingMode":"standard","reportMissingImports":"error"}`
			default:
				if strings.HasPrefix(scenario, "rule-") {
					name = "rules/policy.md"
					mode = 0644
					put(t, root, ".tessl-plugin/plugin.json", `{"name":"other/producer","version":"1.2.3","skills":["skills/example"],"rules":["rules/policy.md"]}`, 0644)
					body = "---\nalwaysApply: false\napplyTo: \"skills/example/** — when checking\"\n---\n# Policy\n"
					switch scenario {
					case "rule-body":
						body += "Read `rules/missing.md` and `skills/example/missing.md`.\n"
					case "rule-metadata":
						body = strings.Replace(body, "---\n# Policy", "example: skills/example/**\n---\n# Policy", 1)
					case "rule-activation-invalid":
						body = strings.Replace(body, "skills/example/**", "../escape/**", 1)
					case "rule-activation-missing-dash":
						body = strings.Replace(body, " — when checking", "", 1)
					}
				}
			}
			put(t, root, name, body, fs.FileMode(mode))
			original := treeAt(t, root)
			_, err := Prepare(opts)
			if err == nil {
				t.Fatal("unsupported runtime/metadata was hidden")
			}
			if !matches(original, treeAt(t, root)) {
				t.Fatal("refusal changed source")
			}
		})
	}
}

func TestConfigurationAndActivationCannotBeWeakenedByProposal(t *testing.T) {
	for _, scenario := range []string{"ignore", "pyright", "activation"} {
		t.Run(scenario, func(t *testing.T) {
			root, opts := fleetFixture(t, fleetCaller)
			opts.Agent = "codex"
			put(t, root, "skills/example/helper.sh", "# tessl install other/producer\nprintf kept\n", 0644)
			name, body, after := ".gitignore", ".tessl/\n!foreign/\n", ".tessl/\n"
			switch scenario {
			case "pyright":
				name = "pyrightconfig.json"
				body = `{"include":["skills/example"],"pythonVersion":"3.12","typeCheckingMode":"standard","reportMissingImports":"error"}`
				after = strings.Replace(body, "standard", "basic", 1)
			case "activation":
				name = "rules/policy.md"
				body = "---\nalwaysApply: false\napplyTo: \"skills/example/** — when checking\"\n---\n# Policy\nRead `skills/example`.\n"
				after = strings.Replace(strings.Replace(body, "skills/example/**", "**/*", 1), "`skills/example`", "`skills/example/SKILL.md`", 1)
				put(t, root, ".tessl-plugin/plugin.json", `{"name":"other/producer","version":"1.2.3","skills":["skills/example"],"rules":["rules/policy.md"]}`, 0644)
			}
			put(t, root, name, body, 0644)
			plan, err := prepareDeterministic(opts, true)
			if err == nil {
				t.Fatal("missing initial semantic refusal")
			}
			_, err = validateProposal(context.Background(), plan, proposal{Edits: []proposedEdit{{Path: name, Action: "replace", BeforeDigest: digest([]byte(body)), Content: after}, {Path: "skills/example/helper.sh", Action: "replace", BeforeDigest: digest([]byte("# tessl install other/producer\nprintf kept\n")), Content: "printf kept\n"}}})
			if err == nil {
				t.Fatal("protected checker/pattern/scope weakened")
			}
			want := "protected path"
			if scenario == "activation" {
				want = "preserve original rule activation scope"
			}
			if !strings.Contains(err.Error(), want) {
				t.Fatalf("wrong refusal: %v", err)
			}
		})
	}
}

func TestTestPathScopeAndForeignAuthority(t *testing.T) {
	for name, want := range map[string]bool{"tests/x.md": true, "skills/a/tests/x.md": true, "contests/x.md": false, "skills/a/tests.md": false} {
		if testPath(name) != want {
			t.Fatalf("wrong test scope: %s", name)
		}
		if got := semanticScope(name); (got == "runtime") != want {
			t.Fatalf("wrong semantic scope: %s %s", name, got)
		}
	}
	root, opts, good := semanticFixture(t)
	put(t, root, "other/plugin/tests/test.py", "# tessl install other/plugin\nassert True\n", 0644)
	plan, err := prepareDeterministic(opts, true)
	if err == nil {
		t.Fatal("missing semantic control")
	}
	if editable(plan, "other/plugin/tests/test.py") {
		t.Fatal("foreign nested tests gained edit authority")
	}
	good.Edits = append(good.Edits, proposedEdit{Path: "other/plugin/tests/test.py", Action: "replace", Content: "assert True\n"})
	if _, err = validateProposal(context.Background(), plan, good); err == nil {
		t.Fatal("foreign nested edit accepted")
	}
}

func TestStandaloneRuleRoleUsesContentWithoutInventingNativePath(t *testing.T) {
	root, opts := fleetFixture(t, fleetCaller)
	opts.Agent = "codex"
	rule := "---\nalwaysApply: true\n---\n# Receipts\nKeep every receipt and report missing evidence.\n"
	put(t, root, ".tessl-plugin/plugin.json", `{"name":"other/producer","version":"1.2.3","skills":["skills/example"],"rules":["rules/receipts.md"]}`, 0644)
	put(t, root, "rules/receipts.md", rule, 0644)
	name := "skills/example/guide.md"
	before := "# Guide\nFollow the receipt obligation in `rules/receipts.md`.\n"
	after := "# Guide\nKeep every receipt and report missing evidence, as required by the receipt rule.\n"
	put(t, root, name, before, 0644)
	plan, err := prepareWithProvider(context.Background(), opts, func(context.Context, string, string) (proposal, AgentRun, error) {
		return proposal{Edits: []proposedEdit{{Path: name, Action: "replace", BeforeDigest: digest([]byte(before)), Content: after}}}, AgentRun{}, nil
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, err = plan.Apply(); err != nil {
		t.Fatal(err)
	}
	if read(t, root, name) != after || read(t, root, "rules/receipts.md") != rule {
		t.Fatal("substantive rule obligation lost")
	}
}
